owner: JobScraper-git
repo: upptime
siteName: Telegram Job Bot Status
siteUrl: https://JobScraper-git.github.io/upptime
commitMessages:
  - 🚀 Uptime check passed
  - ❌ Bot is down
  - 📈 Response time increased

# Sites to monitor
sites:
  - name: Telegram Job Bot
    url: https://jobscraper-a43t.onrender.com
    method: GET
    maxResponseTime: 2000
    expectedStatus: 200
